application: coffeequant
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /statics
  static_dir: statics
  
- url: /reverseconv/.*
  script: reverseconv.app
 
- url: /portfolioanalyzer/.*
  script: portfolio.app

- url: /analytics/.*
  script: analytics.app
 
- url: /pricer/.*
  script: pricer.app

- url: /baskets/.*
  script: baskets.app

- url: /.*
  script: coffeequant.app
  
libraries:
- name: jinja2
  version: latest

- name: numpy
  version: latest
